name: Run tests

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Create local.properties
      run: |
        echo "TMDB_KEY=\"${{ secrets.TMDB_KEY }}\"" > local.properties
        echo "ACCOUNT_ID=${{ secrets.ACCOUNT_ID }}" >> local.properties
        echo "SESSION_ID=\"${{ secrets.SESSION_ID }}\"" >> local.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run unit test
      run: ./gradlew clean testDebug
